name: kubrs_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.3
  collection: ^1.17.1
  cuber: ^0.4.0
  equatable: ^2.0.5
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
