name: kubrs_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.6

dependencies:
  bloc: ^8.1.2
  clock: ^1.1.1
  cloud_firestore: ^4.9.0
  collection: ^1.17.1
  cuber: ^0.4.0
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  intl: ^0.18.0
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  sqflite: ^2.3.0
  url_launcher: ^6.1.12

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons: # dart run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash: # dart run flutter_native_splash:create
  color: "#ffffff"
  image: "assets/splash.png"
  android_12:
    color: "#ffffff"
    image: "assets/splash.png"
