name: kubrs_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.6

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  clock: ^1.1.1
  cloud_firestore: ^4.8.4
  collection: ^1.17.1
  cuber: ^0.4.0
  equatable: ^2.0.5
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
